version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build ./src -c Release
test_script:
- ps: >-
    nuget install NUnit.Runners -OutputDirectory packages
    
    nuget install OpenCover -OutputDirectory packages -Version 4.6.166

    dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools

    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe "-targetargs:"".\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe"" /noshadow" -filter:"+[JustineCore*]*" -output:opencoverCoverage.xml
#   .\src\packages\OpenCover.4.6\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:""src\GameOfLife.NUnit.Tests\bin\$env:CONFIGURATION\GameOfLife.NUnit.Tests.dll"" /noshadow" -filter:"+[GameOfLife*]*" -output:opencoverCoverage.xml

    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID